### ISSUE TITLE
unable to execute ./gpboot_mac: Bad CPU type in executable

### ISSUE THREAD

**Issue by mersay** [evilwombat/gopro-usb-tools#33]
Running on a Apple M2 MBA,
shell is zsh

Device is GoPro Hero 4

Any idea how I can tweak the script?

**Comment by evilwombat** [comment]
I believe the M2 is an ARM architecture, while the Mac version of the tool
is built for x86. You'd basically need to compile gpboot for your
architecture. I'm not really sure how to do this on a Mac these days, but
the only dependency is libusb-1.0. If you can get the libusb library/header
and GCC for your system, you should be able to build the tool using 'make'.
You might need to tweak the Makefile to add the location of libusb on your
system.

**Comment by mersay** [comment]
@evilwombat Thanks for the quick reply, I knew M2 would be a problem. I ran it on my windows PC and it worked. The only "problem" I had was after running the bat file, my camera (hero4 silver) had some message saying that the SETUP queue failed. I removed the card and inserted again, this time I was able to turn the camera on! Thank you so much for your help :) Any link I can buy you a coffee?
