### ISSUE TITLE
GoPro 3+ Black

### ISSUE THREAD

**Issue by adriangibbons** [evilwombat/gopro-usb-tools#7]
Hello, and thanks for putting this up on GitHub. It may be the only way I get my GoPro working again after the best their support team can do is offer me a discount off a new camera!

Using the instructions [here](http://goprouser.freeforums.org/booting-a-hard-bricked-hero3-black-camera-over-usb-danger-t14791.html) with a HD3.03-firmware.bin file I found on the internets. It didn't work with the HD3.11-firmware.bin but I guess that is expected.

> prepare-bootstrap.exe HD3.03-firmware.bin
> gpboot.exe --h3b-rtos h3b-v300-rtos-patched.bin

I am running on Windows 10. Installed the libusb using Zadig etc no worries. Here is how far the script gets:

> Initializing libusb
> Could not set device configuration: -2. Continuing anyway.
> Initializing DDR.......................................... done
> Testing DDR............. FAILED
> Mismatch at DDR offset c0000000: expected 00000000, got ffffffff
> DDR test failed: -1

Any thoughts on how I might get past this point?

Thank you, Adrian.

**Comment by adriangibbons** [comment]
Apologies, I see the instructions are for a Hero 3 Black, not the 3+ Black.

**Comment by evilwombat** [comment]
Hey hey. Cool, glad that you are trying things. As you may have seen
online, the H3 debrick approach won't work on H3+. I only recently wrote a
debricker for Hero3+ Black (and Hero4 Black / Silver, for that matter),
which pretty much take care of reinstalling the firmware more-or-less
automatically. However, I haven't been able to put this online yet, due to
some potential complications with my new/current job (which I like). I am
working though the issues involved, and I hope I will be allowed to put
this stuff out there. In the meantime, hang in there and don't toss that
camera - there is hope :)

**Comment by adriangibbons** [comment]
No worries thanks for getting back to me. I'm getting married in a couple of months and hoping to have this sorted by then as I'd like to use my camera!

**Comment by evilwombat** [comment]
Hello again. I am working though some of the issues with my job, but it
sounds like higher-up people may need to get involved, to see if I'll be
allowed to post this stuff. I want to get the tools out there, but I also
like my job, so I really need to follow the rules here. Stay tuned...

**Comment by adriangibbons** [comment]
Hi, how's it going? Hopefully your employer is a good one. Too often they look for what's in it for them and need convincing why they *should* let you do something rather than why you *should not*!

**Comment by evilwombat** [comment]
Hello. I just checked with my manager regarding my stuff. They are still
looking into it. Hopefully this can be resolved soon. If not, where are you
located?

**Comment by adriangibbons** [comment]
Hey, I am in Perth, Western Australia. You can mail me at adrian.github@gmail.com

**Comment by evilwombat** [comment]
Aww, dang. That's a long way to fly/drive/ship. I was going to offer to
take a look at it, but the shipping sounds like it would be prohibitive.

**Comment by adriangibbons** [comment]
Yeah, just pop over - nice and sunny ;)

TBH, it might be worth shipping it for you to have a look, depending on cost, compared to the price of new GoPro! Email me on the above address and let me know your location and I'll investigate options. Thanks

**Comment by adriangibbons** [comment]
Closing issue as I have been able to run the H3B+ recovery utility. I hasn't fixed my camera tho, probably a hardware issue :(
